#include "cases/support.inc"
#include "cases/device_protocol_cases.inc"
#include "cases/persistence_cases.inc"
#include "cases/manager_scene_cases.inc"
#include "cases/ble_cases.inc"
#include "cases/mesh_light_cases.inc"
#include "cases/test_registry.inc"
