#pragma once

// Embedded Roboto Regular faces for the UI, generated by tools/gen_fonts.sh
// (lv_font_conv, 4bpp). Sizes match what src/ui.cpp uses.

#include <lvgl.h>

LV_FONT_DECLARE(lv_font_roboto_14)
LV_FONT_DECLARE(lv_font_roboto_16)
LV_FONT_DECLARE(lv_font_roboto_20)
