#pragma once

// Compile-time UI font family selection.
//
// Default is Montserrat (bundled with LVGL). Define UI_FONT_ROBOTO (see the
// crowpanel_128_roboto env in platformio.ini) to use the embedded Roboto faces
// generated by tools/gen_fonts.sh. The UI_FONT_* macros below resolve to the
// matching face so src/ui.cpp stays family-agnostic.

#include <lvgl.h>

#ifdef UI_FONT_ROBOTO

LV_FONT_DECLARE(lv_font_roboto_12)
LV_FONT_DECLARE(lv_font_roboto_14)
LV_FONT_DECLARE(lv_font_roboto_16)
LV_FONT_DECLARE(lv_font_roboto_20)

#define UI_FONT_12 (&lv_font_roboto_12)
#define UI_FONT_14 (&lv_font_roboto_14)
#define UI_FONT_16 (&lv_font_roboto_16)
#define UI_FONT_20 (&lv_font_roboto_20)

#else

#define UI_FONT_12 (&lv_font_montserrat_12)
#define UI_FONT_14 (&lv_font_montserrat_14)
#define UI_FONT_16 (&lv_font_montserrat_16)
#define UI_FONT_20 (&lv_font_montserrat_20)

#endif
