#pragma once

// PlatformIO supplies these today. The names intentionally match ESP-IDF
// Kconfig symbols so a future Arduino-as-component build can replace defaults
// without changing driver code.
#ifndef CONFIG_DRIVER_SHARK_NANO_II
#define CONFIG_DRIVER_SHARK_NANO_II 1
#endif

#ifndef CONFIG_DRIVER_CANON_BLE
#define CONFIG_DRIVER_CANON_BLE 0
#endif

#ifndef CONFIG_DRIVER_CANON_TRIGGER
#define CONFIG_DRIVER_CANON_TRIGGER 0
#endif

#ifndef CONFIG_DRIVER_TASCAM_X8
#define CONFIG_DRIVER_TASCAM_X8 0
#endif

#ifndef CONFIG_DRIVER_HOME_ASSISTANT
#define CONFIG_DRIVER_HOME_ASSISTANT 0
#endif

#ifndef CONFIG_DRIVER_AMARAN_LIGHT
#define CONFIG_DRIVER_AMARAN_LIGHT 0
#endif

#ifndef CONFIG_DRIVER_ZHIYUN_X100
#define CONFIG_DRIVER_ZHIYUN_X100 0
#endif

#ifndef CONFIG_MAX_DEVICE_INSTANCES
#define CONFIG_MAX_DEVICE_INSTANCES 24
#endif

#ifndef CONFIG_DEVICE_COMMAND_QUEUE_SIZE
#define CONFIG_DEVICE_COMMAND_QUEUE_SIZE 12
#endif

#ifndef CONFIG_MAX_ACTIVE_LINKS
#define CONFIG_MAX_ACTIVE_LINKS 4
#endif

#ifndef CONFIG_MAX_ACTIVE_INSTANCES
#define CONFIG_MAX_ACTIVE_INSTANCES CONFIG_MAX_ACTIVE_LINKS
#endif

#if defined(CONFIG_BT_NIMBLE_MAX_CONNECTIONS) && \
    CONFIG_MAX_ACTIVE_LINKS > CONFIG_BT_NIMBLE_MAX_CONNECTIONS
#error "CONFIG_MAX_ACTIVE_LINKS cannot exceed CONFIG_BT_NIMBLE_MAX_CONNECTIONS"
#endif

#ifndef CONFIG_BLE_EVENT_QUEUE_SIZE
#define CONFIG_BLE_EVENT_QUEUE_SIZE 16
#endif

#ifndef CONFIG_BLE_ADV_QUEUE_SIZE
#define CONFIG_BLE_ADV_QUEUE_SIZE 8
#endif

#ifndef CONFIG_BLE_ADV_PAYLOAD_SIZE
#define CONFIG_BLE_ADV_PAYLOAD_SIZE 96
#endif

#ifndef CONFIG_BLE_MAX_SKIP_ADDRESSES
#define CONFIG_BLE_MAX_SKIP_ADDRESSES 4
#endif

#ifndef CONFIG_BLE_TX_POWER_DBM
#define CONFIG_BLE_TX_POWER_DBM 6
#endif

#if CONFIG_BLE_TX_POWER_DBM < -24 || CONFIG_BLE_TX_POWER_DBM > 20
#error "CONFIG_BLE_TX_POWER_DBM must be between -24 and 20 dBm"
#endif

#ifndef CONFIG_MAX_SCENES
#define CONFIG_MAX_SCENES 4
#endif

#ifndef CONFIG_MAX_SCENE_STEPS
#define CONFIG_MAX_SCENE_STEPS 8
#endif

#ifndef CONFIG_SCENE_MIN_WAIT_MS
#define CONFIG_SCENE_MIN_WAIT_MS 0
#endif

#ifndef CONFIG_SCENE_MAX_WAIT_MS
#define CONFIG_SCENE_MAX_WAIT_MS 60000
#endif

#ifndef CONFIG_SCENE_CONNECT_TIMEOUT_MS
#define CONFIG_SCENE_CONNECT_TIMEOUT_MS 30000
#endif

#ifndef CONFIG_SCENE_ACTION_TIMEOUT_MS
#define CONFIG_SCENE_ACTION_TIMEOUT_MS 5000
#endif
