#pragma once

// PlatformIO supplies these today. The names intentionally match ESP-IDF
// Kconfig symbols so a future Arduino-as-component build can replace defaults
// without changing driver code.
#ifndef CONFIG_DRIVER_SHARK_NANO_II
#define CONFIG_DRIVER_SHARK_NANO_II 1
#endif

#ifndef CONFIG_DRIVER_CANON_BLE
#define CONFIG_DRIVER_CANON_BLE 0
#endif

#ifndef CONFIG_DRIVER_CANON_TRIGGER
#define CONFIG_DRIVER_CANON_TRIGGER 0
#endif

#ifndef CONFIG_DRIVER_TASCAM_X8
#define CONFIG_DRIVER_TASCAM_X8 0
#endif

#ifndef CONFIG_DRIVER_HOME_ASSISTANT
#define CONFIG_DRIVER_HOME_ASSISTANT 0
#endif

#ifndef CONFIG_DRIVER_APUTURE_LIGHT
#define CONFIG_DRIVER_APUTURE_LIGHT 0
#endif

#ifndef CONFIG_DRIVER_ZHIYUN_X100
#define CONFIG_DRIVER_ZHIYUN_X100 0
#endif

#ifndef CONFIG_DRIVER_GOPRO
#define CONFIG_DRIVER_GOPRO 0
#endif

#ifndef CONFIG_DRIVER_ACTION_CAMERA_RESEARCH
#define CONFIG_DRIVER_ACTION_CAMERA_RESEARCH 0
#endif

// Until dedicated composer toggles land, the action-camera bundle enables the
// two implemented families plus Sony's still-blocked research entry.
#ifndef CONFIG_DRIVER_INSTA360
#define CONFIG_DRIVER_INSTA360 CONFIG_DRIVER_ACTION_CAMERA_RESEARCH
#endif

#ifndef CONFIG_DRIVER_DJI_OSMO
#define CONFIG_DRIVER_DJI_OSMO CONFIG_DRIVER_ACTION_CAMERA_RESEARCH
#endif

#ifndef CONFIG_DRIVER_PHONE_CAMERA
#define CONFIG_DRIVER_PHONE_CAMERA 0
#endif

#define CONFIG_BLE_RUNTIME_ENABLED                                      \
  (CONFIG_DRIVER_SHARK_NANO_II || CONFIG_DRIVER_CANON_BLE ||           \
   CONFIG_DRIVER_CANON_TRIGGER || CONFIG_DRIVER_TASCAM_X8 ||           \
   CONFIG_DRIVER_APUTURE_LIGHT || CONFIG_DRIVER_ZHIYUN_X100 ||         \
   CONFIG_DRIVER_GOPRO || CONFIG_DRIVER_INSTA360 || CONFIG_DRIVER_DJI_OSMO || \
   CONFIG_DRIVER_PHONE_CAMERA)

#ifndef CONFIG_MAX_DEVICE_INSTANCES
#define CONFIG_MAX_DEVICE_INSTANCES 24
#endif

#ifndef CONFIG_DEVICE_COMMAND_QUEUE_SIZE
#define CONFIG_DEVICE_COMMAND_QUEUE_SIZE 12
#endif

#ifndef CONFIG_MAX_ACTIVE_LINKS
#define CONFIG_MAX_ACTIVE_LINKS 4
#endif

#ifndef CONFIG_MAX_ACTIVE_INSTANCES
#define CONFIG_MAX_ACTIVE_INSTANCES CONFIG_MAX_ACTIVE_LINKS
#endif

#if defined(CONFIG_BT_NIMBLE_MAX_CONNECTIONS) && \
    CONFIG_MAX_ACTIVE_LINKS > CONFIG_BT_NIMBLE_MAX_CONNECTIONS
#error "CONFIG_MAX_ACTIVE_LINKS cannot exceed CONFIG_BT_NIMBLE_MAX_CONNECTIONS"
#endif

#ifndef CONFIG_BLE_EVENT_QUEUE_SIZE
#define CONFIG_BLE_EVENT_QUEUE_SIZE 16
#endif

#ifndef CONFIG_BLE_ADV_QUEUE_SIZE
#define CONFIG_BLE_ADV_QUEUE_SIZE 8
#endif

#ifndef CONFIG_BLE_ADV_PAYLOAD_SIZE
#define CONFIG_BLE_ADV_PAYLOAD_SIZE 96
#endif

#ifndef CONFIG_BLE_MAX_SKIP_ADDRESSES
#define CONFIG_BLE_MAX_SKIP_ADDRESSES 4
#endif

#ifndef CONFIG_BLE_TX_POWER_DBM
#define CONFIG_BLE_TX_POWER_DBM 6
#endif

#ifndef CONFIG_BLE_SCAN_INTERVAL_UNITS
#define CONFIG_BLE_SCAN_INTERVAL_UNITS 100
#endif

#ifndef CONFIG_BLE_SCAN_WINDOW_UNITS
#define CONFIG_BLE_SCAN_WINDOW_UNITS 40
#endif

#if CONFIG_BLE_SCAN_INTERVAL_UNITS == 0 || CONFIG_BLE_SCAN_WINDOW_UNITS == 0 || \
    CONFIG_BLE_SCAN_WINDOW_UNITS > CONFIG_BLE_SCAN_INTERVAL_UNITS
#error "BLE scan window must be between 1 and the scan interval"
#endif

#if CONFIG_BLE_TX_POWER_DBM < -24 || CONFIG_BLE_TX_POWER_DBM > 20
#error "CONFIG_BLE_TX_POWER_DBM must be between -24 and 20 dBm"
#endif

#ifndef CONFIG_MAX_SCENE_STEPS
#define CONFIG_MAX_SCENE_STEPS 8
#endif

#ifndef CONFIG_SCENE_MIN_WAIT_MS
#define CONFIG_SCENE_MIN_WAIT_MS 0
#endif

#ifndef CONFIG_SCENE_MAX_WAIT_MS
#define CONFIG_SCENE_MAX_WAIT_MS 60000
#endif

#ifndef CONFIG_SCENE_CONNECT_TIMEOUT_MS
#define CONFIG_SCENE_CONNECT_TIMEOUT_MS 30000
#endif

#ifndef CONFIG_SCENE_PHYSICAL_CONNECT_TIMEOUT_MS
#define CONFIG_SCENE_PHYSICAL_CONNECT_TIMEOUT_MS 60000
#endif

#ifndef CONFIG_SCENE_ACTION_TIMEOUT_MS
#define CONFIG_SCENE_ACTION_TIMEOUT_MS 5000
#endif
