#pragma once

#include <lvgl.h>

// Auto-generated by tools/gen_icons.py — do not edit by hand.

extern const lv_img_dsc_t ui_icon_devices;
extern const lv_img_dsc_t ui_icon_groups;
extern const lv_img_dsc_t ui_icon_scenes;
extern const lv_img_dsc_t ui_icon_portal;
