#!/usr/bin/env python3
"""Convert colorful PNG icons into LVGL TRUE_COLOR_ALPHA C arrays."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


HEADER = """\
#include "assets/ui_icons.h"

#include <lvgl.h>

// Auto-generated by tools/gen_icons.py — do not edit by hand.
"""


def chroma_to_rgba(image: Image.Image) -> Image.Image:
  """Key near-black / near-white backgrounds to transparency."""
  rgba = image.convert("RGBA")
  pixels = list(rgba.getdata())
  w, h = rgba.size

  def sample(x: int, y: int):
    return pixels[y * w + x][:3]

  corners = [
      sample(0, 0),
      sample(w - 1, 0),
      sample(0, h - 1),
      sample(w - 1, h - 1),
  ]
  avg = tuple(sum(c[i] for c in corners) // 4 for i in range(3))
  key_white = sum(avg) > 400

  out = []
  for r, g, b, _a in pixels:
    if key_white:
      # Distance from white.
      dist = (255 - r) + (255 - g) + (255 - b)
      alpha = 0 if dist < 45 else min(255, dist * 3)
    else:
      # Distance from black.
      dist = r + g + b
      alpha = 0 if dist < 36 else min(255, dist * 3)
    if alpha < 16:
      out.append((0, 0, 0, 0))
    else:
      out.append((r, g, b, alpha))
  rgba.putdata(out)
  return rgba


def autocrop(image: Image.Image, pad: int = 2) -> Image.Image:
  alpha = image.split()[-1]
  bbox = alpha.getbbox()
  if bbox is None:
    return image
  left, top, right, bottom = bbox
  left = max(0, left - pad)
  top = max(0, top - pad)
  right = min(image.width, right + pad)
  bottom = min(image.height, bottom + pad)
  cropped = image.crop((left, top, right, bottom))
  # Pad back to square.
  side = max(cropped.width, cropped.height)
  canvas = Image.new("RGBA", (side, side), (0, 0, 0, 0))
  canvas.paste(cropped, ((side - cropped.width) // 2, (side - cropped.height) // 2))
  return canvas


def rgb565(r: int, g: int, b: int) -> int:
  return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def encode_true_color_alpha(image: Image.Image, swap: bool) -> bytes:
  data = bytearray()
  for r, g, b, a in image.getdata():
    color = rgb565(r, g, b)
    if swap:
      color = ((color & 0xFF) << 8) | (color >> 8)
    data.append(color & 0xFF)
    data.append((color >> 8) & 0xFF)
    data.append(a)
  return bytes(data)


def emit_array(name: str, size: int, data_swap0: bytes, data_swap1: bytes) -> str:
  def body(label: str, data: bytes) -> list[str]:
    lines = [f"static const uint8_t {label}[] = {{"]
    row: list[str] = []
    for value in data:
      row.append(f"0x{value:02X}")
      if len(row) == 16:
        lines.append("  " + ", ".join(row) + ",")
        row = []
    if row:
      lines.append("  " + ", ".join(row) + ",")
    lines.append("};")
    return lines

  lines = ["#if LV_COLOR_16_SWAP"]
  lines.extend(body(f"{name}_map", data_swap1))
  lines.append("#else")
  lines.extend(body(f"{name}_map", data_swap0))
  lines.append("#endif")
  lines.append("")
  lines.append(f"const lv_img_dsc_t {name} = {{")
  lines.append("  .header = {")
  lines.append("    .cf = LV_IMG_CF_TRUE_COLOR_ALPHA,")
  lines.append("    .always_zero = 0,")
  lines.append("    .reserved = 0,")
  lines.append(f"    .w = {size},")
  lines.append(f"    .h = {size},")
  lines.append("  },")
  lines.append(f"  .data_size = {len(data_swap0)},")
  lines.append(f"  .data = {name}_map,")
  lines.append("};")
  lines.append("")
  return "\n".join(lines)


def to_image(path: Path, size: int) -> Image.Image:
  image = chroma_to_rgba(Image.open(path))
  image = autocrop(image, pad=8)
  return image.resize((size, size), Image.Resampling.LANCZOS)


def main() -> None:
  parser = argparse.ArgumentParser()
  parser.add_argument("--size", type=int, default=48)
  parser.add_argument("--src", type=Path, default=Path("assets/icons"))
  parser.add_argument("--out-c", type=Path, default=Path("src/assets/ui_icons.c"))
  parser.add_argument("--out-h", type=Path, default=Path("src/assets/ui_icons.h"))
  args = parser.parse_args()

  icons = [
      ("icon_devices", "ui_icon_devices"),
      ("icon_groups", "ui_icon_groups"),
      ("icon_scenes", "ui_icon_scenes"),
      ("icon_portal", "ui_icon_portal"),
      ("icon_cat_motion", "ui_icon_cat_motion"),
      ("icon_cat_lights", "ui_icon_cat_lights"),
      ("icon_cat_cameras", "ui_icon_cat_cameras"),
      ("icon_cat_recorders", "ui_icon_cat_recorders"),
  ]

  parts = [HEADER]
  declarations = [
      "#pragma once",
      "",
      "#include <lvgl.h>",
      "",
      "// Auto-generated by tools/gen_icons.py — do not edit by hand.",
      "",
  ]

  for stem, symbol in icons:
    path = args.src / f"{stem}.png"
    image = to_image(path, args.size)
    data0 = encode_true_color_alpha(image, swap=False)
    data1 = encode_true_color_alpha(image, swap=True)
    parts.append(emit_array(symbol, args.size, data0, data1))
    declarations.append(f"extern const lv_img_dsc_t {symbol};")

  declarations.append("")
  args.out_c.parent.mkdir(parents=True, exist_ok=True)
  args.out_h.parent.mkdir(parents=True, exist_ok=True)
  args.out_c.write_text("\n".join(parts))
  args.out_h.write_text("\n".join(declarations))
  print(f"wrote {args.out_c} ({args.out_c.stat().st_size} bytes)")
  print(f"wrote {args.out_h}")


if __name__ == "__main__":
  main()
