#!/usr/bin/env python3
"""Generate a compact LVGL TRUE_COLOR_ALPHA Ble(e)p wordmark."""

from pathlib import Path

from PIL import Image, ImageFilter

WIDTH = 176
HEIGHT = 58


def encode_true_color_alpha(image: Image.Image, swap: bool) -> bytes:
  data = bytearray()
  for r, g, b, a in image.getdata():
    color = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    if swap:
      color = ((color & 0xFF) << 8) | (color >> 8)
    data.extend((color & 0xFF, (color >> 8) & 0xFF, a))
  return bytes(data)


def array(name: str, data: bytes) -> str:
  lines = [f"static const uint8_t {name}[] = {{"]
  for offset in range(0, len(data), 16):
    row = ", ".join(f"0x{value:02X}" for value in data[offset:offset + 16])
    lines.append(f"  {row},")
  lines.append("};")
  return "\n".join(lines)


def main() -> None:
  # The source already has a transparent background. White-keying it erases
  # the mascot's white eyes and smile, so preserve its authored alpha exactly.
  source = Image.open("assets/bleep_logo.png").convert("RGBA")
  mascot = source.crop((0, 0, 420, source.height))
  wordmark = source.crop((420, 0, source.width, source.height))
  feature_mask = Image.new("L", mascot.size, 0)
  source_pixels = mascot.load()
  mask_pixels = feature_mask.load()
  for y in range(145, 285):
    for x in range(105, 315):
      r, g, b, a = source_pixels[x, y]
      if a > 200 and r > 205 and g > 205 and b > 205:
        mask_pixels[x, y] = 255
  feature_mask = feature_mask.filter(ImageFilter.MaxFilter(9))
  mascot.alpha_composite(
      Image.composite(Image.new("RGBA", mascot.size, (240, 254, 255, 255)),
                      Image.new("RGBA", mascot.size, (0, 0, 0, 0)),
                      feature_mask))
  mascot.thumbnail((58, 58), Image.Resampling.HAMMING)
  wordmark.thumbnail((116, 42), Image.Resampling.HAMMING)
  canvas = Image.new("RGBA", (WIDTH, HEIGHT), (0, 0, 0, 0))
  canvas.alpha_composite(mascot, (0, (HEIGHT - mascot.height) // 2))
  canvas.alpha_composite(wordmark,
                         (60, (HEIGHT - wordmark.height) // 2))
  normal = encode_true_color_alpha(canvas, swap=False)
  swapped = encode_true_color_alpha(canvas, swap=True)

  output = """#include "assets/about_logo.h"

#include <lvgl.h>

// Auto-generated by tools/gen_about_logo.py — do not edit by hand.
#if LV_COLOR_16_SWAP
{swapped}
#else
{normal}
#endif

const lv_img_dsc_t ui_about_logo = {{
  .header = {{
    .cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .always_zero = 0,
    .reserved = 0,
    .w = {width},
    .h = {height},
  }},
  .data_size = {size},
  .data = ui_about_logo_map,
}};
""".format(swapped=array("ui_about_logo_map", swapped),
           normal=array("ui_about_logo_map", normal), width=WIDTH,
           height=HEIGHT, size=len(normal))
  Path("src/assets/about_logo.c").write_text(output)
  Path("src/assets/about_logo.h").write_text("""#pragma once

#include <lvgl.h>

extern const lv_img_dsc_t ui_about_logo;
""")


if __name__ == "__main__":
  main()
