#pragma once

#include <Arduino.h>

namespace portal::assets {

const char kHead[] PROGMEM = R"HTML(<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#090c0d"><title>Ble(e)p Portal</title>)HTML";

const char kStyle[] PROGMEM = R"HTML(<style>
:root{color-scheme:dark;--void:#080a0b;--surface:#101516;--raised:#171d1e;--line:#2a3435;--ink:#edf2ec;--muted:#8e9b98;--cyan:#3ed7e8;--acid:#c8f45d;--warn:#ffb454;--danger:#ff6978;--display:"Avenir Next Condensed","DIN Condensed","Arial Narrow",sans-serif;--mono:"SFMono-Regular",Menlo,Consolas,monospace}
*{box-sizing:border-box}html{background:var(--void)}body{margin:0;min-height:100vh;color:var(--ink);font:14px/1.45 var(--mono);background:radial-gradient(900px 520px at 5% -10%,#15373c 0,transparent 62%),linear-gradient(115deg,transparent 0 49.7%,#15202155 50%,transparent 50.3%),var(--void)}
body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.17;background-image:repeating-linear-gradient(0deg,transparent 0 3px,#fff1 4px)}button,input,select{font:inherit}button{cursor:pointer}.shell{min-height:100vh;display:grid;grid-template-columns:238px minmax(0,1fr)}
aside{position:sticky;top:0;height:100vh;padding:28px 20px;border-right:1px solid var(--line);background:#090d0ee8;backdrop-filter:blur(18px);display:flex;flex-direction:column;z-index:4}.brand-logo{display:block;width:178px;height:auto;filter:drop-shadow(0 8px 18px #0009)}.eyebrow{margin-top:9px;color:var(--muted);font-size:10px;letter-spacing:.18em;text-transform:uppercase}.nav{display:grid;gap:7px;margin:42px 0}.nav button{display:flex;align-items:center;gap:11px;width:100%;border:1px solid transparent;border-radius:8px;background:transparent;color:var(--muted);padding:11px;text-align:left}.nav button:before{content:"";width:7px;height:7px;border:1px solid currentColor;transform:rotate(45deg)}.nav button.active{color:var(--ink);background:var(--raised);border-color:var(--line)}.nav button.active:before{background:var(--cyan);border-color:var(--cyan);box-shadow:0 0 14px var(--cyan)}
.portal-life{margin-top:auto;border-top:1px solid var(--line);padding-top:18px}.life-row{display:flex;justify-content:space-between;color:var(--muted);font-size:11px}.meter{height:3px;background:#273031;margin:10px 0 16px;overflow:hidden}.meter i{display:block;height:100%;width:100%;background:var(--acid);transition:width .5s}.exit{width:100%;border:1px solid #62323a;background:#241317;color:#ff9aa5;border-radius:7px;padding:10px}
main{min-width:0;padding:42px clamp(22px,5vw,68px) 80px}.topline{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:35px}.kicker{color:var(--cyan);font-size:10px;letter-spacing:.22em;text-transform:uppercase}.topline h1{font:800 clamp(34px,5vw,64px)/.94 var(--display);letter-spacing:.02em;text-transform:uppercase;margin:7px 0 0}.status{display:flex;align-items:center;gap:8px;border:1px solid var(--line);border-radius:999px;padding:8px 12px;color:var(--muted);white-space:nowrap}.status i{width:7px;height:7px;border-radius:50%;background:var(--acid);box-shadow:0 0 12px var(--acid)}
.view{display:none;animation:arrive .32s ease both}.view.active{display:block}@keyframes arrive{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px}.panel{grid-column:span 12;background:linear-gradient(135deg,#151b1cfa,#0e1213fa);border:1px solid var(--line);border-radius:12px;padding:20px;box-shadow:0 22px 50px #0005}.panel.half{grid-column:span 6}.panel.third{grid-column:span 4}.panel h2{font:700 18px/1.1 var(--display);letter-spacing:.08em;text-transform:uppercase;margin:0 0 16px}.metric{font:800 42px/1 var(--display);color:var(--acid)}.metric-label{margin-top:8px;color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.12em}
.toolbar{display:flex;gap:10px;justify-content:space-between;align-items:center;margin:0 0 15px}.toolbar p{margin:0;color:var(--muted)}.button{border:0;border-radius:7px;padding:10px 14px;background:var(--cyan);color:#041012;font-weight:800}.button.secondary{background:#263031;color:var(--ink);border:1px solid #3b4748}.button.ghost{background:transparent;color:var(--muted);border:1px solid var(--line)}.button.danger{background:#4a1f27;color:#ffc0c6}.button:disabled{opacity:.45;cursor:not-allowed}
.cards{display:grid;gap:10px}.card{border:1px solid var(--line);border-radius:9px;background:#0c1011;padding:16px}.card-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.card-title{font:700 20px/1.1 var(--display);letter-spacing:.04em}.meta{color:var(--muted);font-size:11px;margin-top:5px}.badges{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.badge{border:1px solid #354142;border-radius:999px;padding:4px 7px;color:var(--muted);font-size:9px;letter-spacing:.1em;text-transform:uppercase}.badge.on{border-color:#49641c;color:var(--acid)}.badge.warn{border-color:#79572c;color:var(--warn)}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}
.field-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field{display:grid;gap:6px}.field.full{grid-column:1/-1}label{color:var(--muted);font-size:10px;letter-spacing:.1em;text-transform:uppercase}input,select{width:100%;border:1px solid #354143;border-radius:7px;background:#090c0d;color:var(--ink);padding:10px}input:focus,select:focus{outline:2px solid #3ed7e855;border-color:var(--cyan)}.switch{display:flex;gap:9px;align-items:center;color:var(--ink);font-size:12px;text-transform:none;letter-spacing:0}.switch input{width:auto}
.split{display:grid;grid-template-columns:minmax(220px,310px) minmax(0,1fr);gap:16px}.list-button{width:100%;text-align:left;border:1px solid var(--line);border-radius:8px;background:#0d1112;color:var(--ink);padding:13px;margin-bottom:8px}.list-button.active{border-color:var(--cyan);box-shadow:inset 3px 0 var(--cyan)}.tabs{display:flex;gap:5px;border-bottom:1px solid var(--line);margin-bottom:14px}.tabs button{border:0;background:transparent;color:var(--muted);padding:10px 14px;border-bottom:2px solid transparent}.tabs button.active{color:var(--ink);border-color:var(--cyan)}.step{display:grid;grid-template-columns:32px 1fr auto;gap:10px;align-items:center;border:1px solid var(--line);border-radius:8px;padding:11px;margin:8px 0;background:#0b0f10}.step-index{color:var(--cyan);font:700 18px var(--display)}.step strong{display:block}.step small{color:var(--muted)}.step-tools{display:flex;gap:5px}.icon-button{border:1px solid var(--line);background:#171d1e;color:var(--muted);border-radius:5px;padding:5px 8px}.empty{border:1px dashed #344143;border-radius:9px;color:var(--muted);padding:24px;text-align:center}
.notice{border-left:3px solid var(--warn);background:#251d12;padding:12px 14px;color:#efcf9e;margin-bottom:16px}.toast{position:fixed;right:22px;bottom:22px;max-width:min(420px,calc(100vw - 44px));background:#172021;border:1px solid #415052;border-radius:9px;padding:13px 16px;box-shadow:0 18px 55px #000b;transform:translateY(20px);opacity:0;pointer-events:none;transition:.22s;z-index:9}.toast.show{transform:none;opacity:1}.toast.bad{border-color:#71313b;color:#ffafb8}
dialog{width:min(520px,calc(100vw - 28px));border:1px solid #3b494a;border-radius:12px;background:#111718;color:var(--ink);padding:0;box-shadow:0 30px 90px #000d}dialog::backdrop{background:#020404cc;backdrop-filter:blur(4px)}.dialog-body{padding:22px}.dialog-body h2{font:800 24px var(--display);text-transform:uppercase;margin:0 0 18px}.dialog-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:20px}
@media(max-width:840px){.shell{display:block}aside{position:sticky;height:auto;padding:10px 16px 12px;border-right:0;border-bottom:1px solid var(--line);display:grid;grid-template-columns:1fr auto;align-items:center}.eyebrow,.portal-life .life-row,.portal-life .meter{display:none}.brand-logo{width:132px}.nav{grid-column:1/-1;display:flex;overflow:auto;margin:8px -4px 0}.nav button{width:auto;white-space:nowrap;padding:8px 10px}.portal-life{position:absolute;right:16px;top:12px;margin:0;padding:0;border:0}.exit{width:auto;padding:8px 10px}.topline{margin-bottom:24px}.topline h1{font-size:42px}.status{display:none}main{padding:28px 16px 70px}.panel.half,.panel.third{grid-column:span 12}.split{grid-template-columns:1fr}.field-grid{grid-template-columns:1fr}.field.full{grid-column:auto}}
@media(max-width:520px){.toolbar,.card-head{align-items:stretch;flex-direction:column}.badges{justify-content:flex-start}.step{grid-template-columns:28px 1fr}.step-tools{grid-column:2;justify-content:flex-start}.panel{padding:15px}.nav button:before{display:none}}
</style>)HTML";

const char kBody[] PROGMEM = R"HTML(</head><body><div class="shell"><aside><div><img class="brand-logo" src="/assets/bleep-logo.webp" width="320" height="98" alt="Ble(e)p"><div class="eyebrow">Temporary field console</div></div><nav class="nav"><button data-view="overview" class="active">Overview</button><button data-view="devices">Devices</button><button data-view="sequences">Sequences</button><button data-view="wifi">Wi-Fi</button><button data-view="assistant">Home Assistant</button></nav><div class="portal-life"><div class="life-row"><span>Portal window</span><span id="lifeText">10:00</span></div><div class="meter"><i id="lifeMeter"></i></div><button class="exit" id="exitPortal">Finish &amp; exit</button></div></aside><main><header class="topline"><div><div class="kicker">Studio configuration / local only</div><h1 id="pageTitle">Overview</h1></div><div class="status"><i></i><span>Panel-authorized session</span></div></header>
<section id="overview" class="view active"><div class="grid"><article class="panel third"><div class="metric" id="deviceMetric">—</div><div class="metric-label">Configured devices</div></article><article class="panel third"><div class="metric" id="sequenceMetric">—</div><div class="metric-label">Authored sequences</div></article><article class="panel third"><div class="metric">PAUSED</div><div class="metric-label">Device connections</div></article><article class="panel half"><h2>Configuration bay</h2><p>Rename and organize devices or compose Start and Stop sequences directly through this Portal. Studio Wi-Fi is optional for those changes.</p><div class="actions"><button class="button" data-jump="devices">Manage devices</button><button class="button secondary" data-jump="sequences">Edit sequences</button></div></article><article class="panel half"><h2>Panel link</h2><div class="notice" id="networkNotice">Reading Portal network…</div><p class="meta" id="panelIdentity">Panel identity loading…</p><p class="meta">Physical links and sequence execution stay suspended while this console is open.</p></article></div></section>
<section id="devices" class="view"><div class="toolbar"><p>Committed devices in this firmware and dormant records.</p><button class="button secondary" data-jump="assistant">+ HA entity</button></div><div id="deviceCards" class="cards"><div class="empty">Loading device registry…</div></div></section>
<section id="sequences" class="view"><div class="toolbar"><p>Ordered Start and Stop actions. Execution remains on the panel.</p><button class="button" id="newSequence">+ New sequence</button></div><div class="split"><div class="panel"><div id="sequenceList"></div></div><div class="panel" id="sequenceEditor"><div class="empty">Choose a sequence to edit.</div></div></div></section>
<section id="wifi" class="view"><div class="grid"><form id="wifiForm" class="panel half"><h2>Studio Wi-Fi</h2><p class="meta">Wi-Fi is needed only for Home Assistant. Device and sequence settings work on the Ble(e)p setup network.</p><button id="scanWifi" class="button secondary" type="button">Show nearby Wi-Fi</button><div id="networks" class="cards"></div><div class="field-grid"><div class="field full"><label>Wi-Fi SSID</label><input name="ssid" required maxlength="32" autocomplete="off"></div><div class="field full"><label>Wi-Fi password</label><input name="password" type="password" maxlength="64" autocomplete="current-password"></div></div><div class="actions"><button id="connectWifi" class="button">Connect Wi-Fi</button></div><div id="wifiFeedback" class="notice">Ready.</div></form><article class="panel half"><h2>What changes</h2><p>After Ble(e)p joins, this open setup network closes. Reconnect your phone or computer to the studio network, then open the numeric address shown on the panel.</p><p class="meta">Every device and sequence change already saved through this setup Portal remains stored.</p></article></div></section>
<section id="assistant" class="view"><div id="haNetworkNotice" class="notice">Home Assistant setup requires Ble(e)p and this browser to be on the studio network.</div><div class="grid"><form id="haForm" class="panel half"><h2>Home Assistant link</h2><div class="field-grid"><div class="field full"><label>Local URL</label><input name="url" value="http://homeassistant.local:8123" required></div><div class="field full"><label>Long-lived token</label><input name="token" type="password" autocomplete="new-password" placeholder="Paste a long-lived access token"><button id="changeToken" class="button ghost" type="button" hidden>Change stored token</button></div></div><div class="actions"><button class="button">Save link &amp; entities</button></div></form><article class="panel half"><h2>Entity finder</h2><div class="field"><label>Search</label><input id="haQuery" placeholder="Key Light or light.key_light"></div><div class="actions"><button class="button secondary" id="findEntities">Scan supported entities</button></div><div id="entityResults" class="cards"></div></article><article class="panel"><h2>Entity rack / max 4</h2><div id="entitySlots" class="field-grid"></div></article></div></section>
</main></div><div id="toast" class="toast"></div><dialog id="stepDialog"><form method="dialog" class="dialog-body"><h2 id="stepTitle">Add step</h2><div class="field-grid"><div class="field"><label>Step type</label><select id="stepKind"><option value="action">Device action</option><option value="wait">Wait</option></select></div><div class="field wait-field"><label>Duration / ms</label><input id="stepWait" type="number" min="0" max="60000" value="200"></div><div class="field action-field"><label>Device</label><select id="stepDevice"></select></div><div class="field action-field"><label>Action</label><select id="stepCommand"></select></div><div class="field action-field"><label id="value0Label">Value 1</label><input id="stepValue0" type="number" value="0"></div><div class="field action-field"><label id="value1Label">Value 2</label><input id="stepValue1" type="number" value="0"></div><div class="field action-field"><label id="value2Label">Value 3</label><input id="stepValue2" type="number" value="0"></div></div><div class="dialog-actions"><button class="button ghost" value="cancel">Cancel</button><button class="button" id="saveStep" value="default">Save step</button></div></form></dialog>
<script>
const nonce=window.PORTAL_NONCE,state={devices:[],sequences:[],current:null,tab:'start',editStep:-1,creatingSequence:false,remaining:600,lan:false};const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opt={}){let headers={...(opt.headers||{})};if(opt.body&&typeof opt.body!=='string'){headers['Content-Type']='application/json';opt.body=JSON.stringify(opt.body)}if(opt.method&&opt.method!=='GET')headers['X-Portal-Nonce']=nonce;let r=await fetch(path,{...opt,headers}),type=r.headers.get('content-type')||'',data=type.includes('json')?await r.json():await r.text();if(!r.ok)throw new Error(data.message||data.error||data||`Request failed (${r.status})`);state.remaining=600;return data}
function toast(message,bad=false){let t=$('#toast');t.textContent=message;t.className='toast show'+(bad?' bad':'');clearTimeout(t.timer);t.timer=setTimeout(()=>t.className='toast',3200)}
function showView(id){document.querySelectorAll('.view,.nav button').forEach(n=>n.classList.remove('active'));$('#'+id).classList.add('active');document.querySelector(`.nav button[data-view="${id}"]`).classList.add('active');$('#pageTitle').textContent=id==='assistant'?'Home Assistant':id==='wifi'?'Wi-Fi':id[0].toUpperCase()+id.slice(1);if(id==='devices')loadDevices();if(id==='sequences')loadSequences();if(id==='wifi')loadWifi();if(id==='assistant')loadHa()}
document.querySelectorAll('[data-view],[data-jump]').forEach(b=>b.onclick=()=>showView(b.dataset.view||b.dataset.jump));setInterval(()=>{state.remaining=Math.max(0,state.remaining-1);let m=Math.floor(state.remaining/60),s=String(state.remaining%60).padStart(2,'0');$('#lifeText').textContent=`${m}:${s}`;$('#lifeMeter').style.width=(state.remaining/6)+'%'},1000);
async function loadSummary(){try{let d=await api('/api/summary');state.lan=!!d.lan;$('#deviceMetric').textContent=`${d.devices}/${d.device_capacity}`;$('#sequenceMetric').textContent=d.sequences;$('#panelIdentity').textContent=d.panel_id;$('#networkNotice').textContent=state.lan?'Studio LAN · '+d.network:'Setup AP · '+d.network;$('#haNetworkNotice').style.display=state.lan?'none':'block';document.querySelectorAll('#assistant button,#assistant input').forEach(x=>x.disabled=!state.lan)}catch(e){toast(e.message,true)}}
function deviceName(id){return state.devices.find(d=>d.id===id)?.name||`Device ${id}`}
async function loadDevices(){try{let d=await api('/api/devices');state.devices=d.devices||[];renderDevices();loadSummary()}catch(e){toast(e.message,true)}}
function renderDevices(){let root=$('#deviceCards');if(!state.devices.length){root.innerHTML='<div class="empty">No configured devices. Add physical devices on the panel or add Home Assistant entities here.</div>';return}root.innerHTML=state.devices.map(d=>`<article class="card" data-device="${d.id}"><div class="card-head"><div><div class="card-title">${esc(d.name)}</div><div class="meta">${esc(d.driver)} · instance ${d.id}${d.entity_id?' · '+esc(d.entity_id):''}</div></div><div class="badges"><span class="badge ${d.enabled?'on':''}">${d.enabled?'enabled':'disabled'}</span><span class="badge ${d.driver_available?'':'warn'}">${d.driver_available?'compiled':'dormant'}</span>${d.paired?'<span class="badge on">paired</span>':''}</div></div><div class="actions"><button class="button secondary" onclick="editDevice(${d.id})">Rename</button><button class="button ghost" onclick="toggleDevice(${d.id})">${d.enabled?'Disable':'Enable'}</button><button class="button danger" onclick="removeDevice(${d.id})">Remove</button></div></article>`).join('')}
async function editDevice(id){let d=state.devices.find(x=>x.id===id),name=prompt('Panel name',d.name);if(name===null)return;try{await api('/api/devices/'+id,{method:'PATCH',body:{revision:d.revision,name,enabled:d.enabled}});toast('Device updated');loadDevices()}catch(e){toast(e.message,true)}}
async function toggleDevice(id){let d=state.devices.find(x=>x.id===id);try{await api('/api/devices/'+id,{method:'PATCH',body:{revision:d.revision,name:d.name,enabled:!d.enabled}});toast(d.enabled?'Device disabled':'Device enabled');loadDevices()}catch(e){toast(e.message,true)}}
async function removeDevice(id){let d=state.devices.find(x=>x.id===id);if(!confirm(`Remove “${d.name}” from Ble(e)p? Pairing identity may also be cleared.`))return;try{await api('/api/devices/'+id,{method:'DELETE',body:{revision:d.revision}});toast('Device removed');loadDevices()}catch(e){toast(e.message,true)}}
async function loadSequences(selectId){try{let d=await api('/api/sequences');state.sequences=d.sequences||[];if(selectId)state.current=state.sequences.find(s=>s.id===selectId)||null;else if(state.current)state.current=state.sequences.find(s=>s.id===state.current.id)||null;renderSequenceList();renderSequenceEditor();loadSummary()}catch(e){toast(e.message,true)}}
function renderSequenceList(){let root=$('#sequenceList');if(!state.sequences.length){root.innerHTML='<div class="empty">No sequences yet.</div>';return}root.innerHTML=state.sequences.map(s=>`<button class="list-button ${state.current?.id===s.id?'active':''}" onclick="selectSequence(${s.id})"><strong>${esc(s.name)}</strong><div class="meta">${s.start.length} Start · ${s.stop.length} ${s.stop_mode==='generated'?'generated':'custom'} Stop · ${s.enabled?'enabled':'disabled'}</div></button>`).join('')}
function selectSequence(id){state.current=JSON.parse(JSON.stringify(state.sequences.find(s=>s.id===id)));state.tab='start';state.creatingSequence=false;renderSequenceList();renderSequenceEditor()}
function stepText(s){if(s.kind==='wait')return [`Wait`,`${s.wait_ms} ms`];let vals=(s.command==='set_light_cct'||s.command==='set_light_cct_and_on')?` · ${s.value0}K / ${s.value1}% / tint ${s.value2}`:(s.command==='set_light_rgb'||s.command==='set_light_rgb_and_on')?` · #${Number(s.value0).toString(16).padStart(6,'0')} / ${s.value1}%`:'';return [deviceName(s.target_id),s.label+vals]}
function generatedStop(start){let inverse={record_start:['record_stop','Record stop'],record_stop:['record_start','Record start'],turn_on:['turn_off','Turn off'],turn_off:['turn_on','Turn on'],set_light_cct_and_on:['turn_off','Turn off'],set_light_rgb_and_on:['turn_off','Turn off'],record_trigger:['record_trigger','Record trigger'],press:['press','Press'],activate:['activate','Activate']};return [...start].reverse().flatMap(x=>{if(x.kind==='wait')return [{...x}];let mapped=inverse[x.command];return mapped?[{...x,command:mapped[0],label:mapped[1]}]:[]})}
function syncGeneratedStop(){if(state.current?.stop_mode==='generated')state.current.stop=generatedStop(state.current.start)}
function customizeStop(){captureSceneHeader();state.current.stop_mode='custom';renderSequenceEditor()}
function useGeneratedStop(){captureSceneHeader();if(!confirm('Discard the custom Stop and use the generated Stop?'))return;state.current.stop_mode='generated';syncGeneratedStop();renderSequenceEditor()}
function reviewGeneratedStop(){captureSceneHeader();if(!state.current.start.length){toast('Add at least one Start step first',true);return}syncGeneratedStop();state.tab='stop';renderSequenceEditor()}
async function finishNewSequence(){if(!state.current.start.length){toast('Add at least one Start step first',true);return}let name=prompt('Sequence name',state.current.name);if(!name)return;state.current.name=name;$('#sceneName').value=name;await saveSequence(true)}
function renderSequenceEditor(){let root=$('#sequenceEditor'),s=state.current;if(!s){root.innerHTML='<div class="empty">Choose a sequence to edit.</div>';return}let list=s[state.tab],generated=state.tab==='stop'&&s.stop_mode==='generated',creating=state.creatingSequence,tools=generated?'':`<div class="step-tools"><button class="icon-button" onclick="moveStep(INDEX,-1)">↑</button><button class="icon-button" onclick="moveStep(INDEX,1)">↓</button><button class="icon-button" onclick="openStep(INDEX)">Edit</button><button class="icon-button" onclick="deleteStep(INDEX)">×</button></div>`,modeAction=generated?'<button class="button secondary" onclick="customizeStop()">Customize Stop</button>':`<button class="button secondary" onclick="openStep(-1)">+ Add step</button>${state.tab==='stop'?'<button class="button ghost" onclick="useGeneratedStop()">Use generated Stop</button>':''}`,actions=creating?(state.tab==='start'?`${modeAction}<button class="button" onclick="reviewGeneratedStop()" ${s.start.length?'':'disabled'}>Next: review Stop</button>`:`${modeAction}<button class="button" onclick="finishNewSequence()">Finish sequence</button>`):`${modeAction}<button class="button" onclick="saveSequence()">Save sequence</button><button class="button ghost" onclick="duplicateSequence()">Duplicate</button><button class="button danger" onclick="deleteSequence()">Delete</button>`;root.innerHTML=`${creating?`<div class="notice">${state.tab==='start'?'Add Start actions.':'Review generated Stop or customize it.'}</div>`:''}<div class="field-grid" ${creating?'style="display:none"':''}><div class="field full"><label>Sequence name</label><input id="sceneName" maxlength="31" value="${esc(s.name)}"></div><label class="switch"><input id="sceneEnabled" type="checkbox" ${s.enabled?'checked':''}> Enabled on panel</label></div><div class="tabs"><button class="${state.tab==='start'?'active':''}" onclick="setSceneTab('start')">Start / ${s.start.length}</button><button class="${state.tab==='stop'?'active':''}" onclick="setSceneTab('stop')" ${creating&&!s.start.length?'disabled':''}>${creating?'Stop':(s.stop_mode==='generated'?'Generated':'Custom')+' Stop'} / ${s.stop.length}</button></div><div id="steps">${list.length?list.map((x,i)=>{let t=stepText(x);return `<div class="step"><div class="step-index">${String(i+1).padStart(2,'0')}</div><div><strong>${esc(t[0])}</strong><small>${esc(t[1])}</small></div>${tools.replaceAll('INDEX',i)}</div>`}).join(''):`<div class="empty">${generated?'No generated Stop actions.':'No '+state.tab+' steps.'}</div>`}</div><div class="actions">${actions}</div>`}
function setSceneTab(tab){state.tab=tab;renderSequenceEditor()}function captureSceneHeader(){if(!state.current)return;state.current.name=$('#sceneName')?.value||state.current.name;state.current.enabled=$('#sceneEnabled')?.checked??state.current.enabled}
function moveStep(i,d){captureSceneHeader();let a=state.current[state.tab],j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];syncGeneratedStop();renderSequenceEditor()}function deleteStep(i){captureSceneHeader();state.current[state.tab].splice(i,1);syncGeneratedStop();renderSequenceEditor()}
function syncStepFields(){let wait=$('#stepKind').value==='wait';document.querySelectorAll('.wait-field').forEach(n=>n.style.display=wait?'grid':'none');document.querySelectorAll('.action-field').forEach(n=>n.style.display=wait?'none':'grid');if(!wait)syncCommands()}
function syncCommands(){let id=Number($('#stepDevice').value),d=state.devices.find(x=>x.id===id),sel=$('#stepCommand'),old=sel.value;sel.innerHTML=(d?.actions||[]).map(a=>`<option value="${a.id}">${esc(a.label)}</option>`).join('');if([...sel.options].some(o=>o.value===old))sel.value=old;syncValueLabels()}
function syncValueLabels(){let c=$('#stepCommand').value,labels=(c==='set_light_cct'||c==='set_light_cct_and_on')?['Kelvin','Brightness / %','Tint / -1000…1000']:(c==='set_light_rgb'||c==='set_light_rgb_and_on')?['RGB / decimal','Brightness / %','Unused']:['Unused','Unused','Unused'];['value0Label','value1Label','value2Label'].forEach((id,i)=>$('#'+id).textContent=labels[i]);['stepValue0','stepValue1','stepValue2'].forEach((id,i)=>$('#'+id).disabled=labels[i]==='Unused')}
function openStep(index){captureSceneHeader();if(state.tab==='stop'&&state.current.stop_mode==='generated')return;state.editStep=index;let existing=index>=0?state.current[state.tab][index]:null;$('#stepTitle').textContent=existing?'Edit step':'Add step';$('#stepKind').value=existing?.kind||'action';$('#stepDevice').innerHTML=state.devices.filter(d=>d.enabled&&d.driver_available&&d.actions.length).map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('');if(existing?.target_id)$('#stepDevice').value=existing.target_id;syncStepFields();if(existing?.command)$('#stepCommand').value=existing.command;syncValueLabels();$('#stepWait').value=existing?.wait_ms??200;let c=$('#stepCommand').value,cct=!existing&&c==='set_light_cct_and_on',rgb=!existing&&c==='set_light_rgb_and_on';$('#stepValue0').value=existing?.value0??(cct?5600:rgb?16777215:0);$('#stepValue1').value=existing?.value1??((cct||rgb)?50:0);$('#stepValue2').value=existing?.value2??0;$('#stepDialog').showModal()}
$('#stepKind').onchange=syncStepFields;$('#stepDevice').onchange=syncCommands;$('#stepCommand').onchange=()=>{syncValueLabels();let c=$('#stepCommand').value;if(c==='set_light_cct_and_on'){ $('#stepValue0').value=5600;$('#stepValue1').value=50;$('#stepValue2').value=0 }else if(c==='set_light_rgb_and_on'){ $('#stepValue0').value=16777215;$('#stepValue1').value=50;$('#stepValue2').value=0 }};$('#saveStep').onclick=e=>{e.preventDefault();let step=$('#stepKind').value==='wait'?{kind:'wait',wait_ms:Number($('#stepWait').value)}:{kind:'action',target_id:Number($('#stepDevice').value),command:$('#stepCommand').value,value0:Number($('#stepValue0').value)||0,value1:Number($('#stepValue1').value)||0,value2:Number($('#stepValue2').value)||0,label:$('#stepCommand').selectedOptions[0]?.textContent||''};if(state.editStep<0)state.current[state.tab].push(step);else state.current[state.tab][state.editStep]=step;syncGeneratedStop();$('#stepDialog').close();renderSequenceEditor()};
async function saveSequence(finish=false){captureSceneHeader();try{let s=await api('/api/sequences/'+state.current.id,{method:'PUT',body:state.current});state.creatingSequence=false;toast(finish?'Sequence ready':'Sequence saved');await loadSequences(s.id)}catch(e){toast(e.message,true)}}async function deleteSequence(){if(!confirm(`Delete “${state.current.name}”?`))return;try{await api('/api/sequences/'+state.current.id,{method:'DELETE',body:{revision:state.current.revision}});state.current=null;state.creatingSequence=false;toast('Sequence deleted');loadSequences()}catch(e){toast(e.message,true)}}
async function duplicateSequence(){let name=prompt('Name for the copy',state.current.name+' copy');if(!name)return;try{let s=await api('/api/sequences',{method:'POST',body:{name,source_id:state.current.id}});await loadSequences(s.id);toast('Sequence duplicated')}catch(e){toast(e.message,true)}}
$('#newSequence').onclick=async()=>{try{let s=await api('/api/sequences',{method:'POST',body:{name:'New sequence'}});await loadSequences(s.id);state.creatingSequence=true;state.tab='start';renderSequenceEditor();toast('Add the Start steps')}catch(e){toast(e.message,true)}};
function wifiMessage(text,bad=false){let n=$('#wifiFeedback');n.textContent=text;n.style.borderColor=bad?'var(--danger)':'var(--warn)'}
async function loadWifi(){await loadSummary();if(state.lan){$('#wifiForm').querySelectorAll('button,input').forEach(x=>x.disabled=true);wifiMessage('Connected to studio Wi-Fi. Use the panel Settings screen to forget or replace it later.');return}$('#wifiForm').querySelectorAll('button,input').forEach(x=>x.disabled=false);scanWifi()}
async function scanWifi(){let scan=$('#scanWifi'),root=$('#networks');scan.disabled=true;root.innerHTML='<div class="empty">Loading Portal-entry scan…</div>';try{await api('/api/wifi/scan',{method:'POST',body:{}});let d=await api('/api/wifi/scan');root.innerHTML=(d.networks||[]).map(n=>`<button type="button" class="list-button" data-ssid="${esc(n.ssid)}" onclick="chooseWifi(this.dataset.ssid)"><strong>${esc(n.ssid)}</strong><div class="meta">${n.rssi} dBm · ${n.secure?'secured':'open'}</div></button>`).join('')||'<div class="empty">No networks found. Enter the SSID manually.</div>';wifiMessage('Nearby networks were scanned before the setup AP opened.')}catch(e){root.innerHTML='<div class="empty">Enter the SSID manually.</div>';wifiMessage(e.message,true)}finally{scan.disabled=false}}
function chooseWifi(ssid){$('#wifiForm [name=ssid]').value=ssid;$('#wifiForm [name=password]').focus()}
$('#scanWifi').onclick=scanWifi;$('#wifiForm').onsubmit=async e=>{e.preventDefault();let connect=$('#connectWifi');connect.disabled=true;wifiMessage('Connecting to studio Wi-Fi…');try{let r=await fetch('/wifi',{method:'POST',headers:{'X-Portal-Nonce':nonce},body:new URLSearchParams(new FormData(e.currentTarget))}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not start connection');pollWifi()}catch(e){wifiMessage(e.message,true);connect.disabled=false}};
async function pollWifi(){try{let r=await fetch('/api/wifi/status'),d=await r.json();wifiMessage(d.message,d.state==='failed');if(d.state==='connecting'){setTimeout(pollWifi,500);return}$('#connectWifi').disabled=false;if(d.state==='connected')wifiMessage('Connected. Rejoin '+d.ssid+' on this device, then open '+d.url+'.')}catch(e){wifiMessage('The setup AP closed. Rejoin studio Wi-Fi and use the address on the panel.')}}
function makeSlots(){let root=$('#entitySlots');root.innerHTML='';for(let i=0;i<4;i++)root.insertAdjacentHTML('beforeend',`<div class="field"><label>Entity ${i+1}</label><input form="haForm" name="id${i}" autocomplete="off" placeholder="light.key_light"><input form="haForm" name="instance${i}" type="hidden"></div><div class="field"><label>Panel name</label><input form="haForm" name="name${i}" autocomplete="off" placeholder="Key Light"></div>`)}makeSlots();
async function loadHa(){await loadSummary();try{let d=await api('/api/config'),token=$('#haForm [name=token]'),change=$('#changeToken');$('#haForm [name=url]').value=d.url||'http://homeassistant.local:8123';token.value='';token.disabled=!!d.token_stored||!state.lan;token.placeholder=d.token_stored?'Token stored on Ble(e)p':'Paste a long-lived access token';change.hidden=!d.token_stored;change.disabled=!state.lan;for(let i=0;i<4;i++)['id','name','instance'].forEach(k=>$('#entitySlots [name='+k+i+']').value='');(d.entities||[]).forEach((e,i)=>{if(i>3)return;$('#entitySlots [name=id'+i+']').value=e.entity_id;$('#entitySlots [name=name'+i+']').value=e.name;$('#entitySlots [name=instance'+i+']').value=e.instance_id})}catch(e){toast(e.message,true)}}
$('#changeToken').onclick=()=>{let token=$('#haForm [name=token]');token.disabled=false;token.placeholder='Paste replacement token';token.focus();$('#changeToken').hidden=true};
$('#findEntities').onclick=async e=>{e.preventDefault();let form=$('#haForm'),p=new URLSearchParams({q:$('#haQuery').value,url:form.url.value,token:form.token.value});$('#entityResults').innerHTML='<div class="empty">Scanning Home Assistant…</div>';try{let d=await api('/api/entities',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p.toString()});state.entityResults=d.entities||[];$('#entityResults').innerHTML=state.entityResults.map((x,i)=>`<button class="list-button" onclick="chooseEntityResult(${i})"><strong>${esc(x.name)}</strong><div class="meta">${esc(x.entity_id)} · ${esc(x.state)}</div></button>`).join('')||'<div class="empty">No supported matches.</div>'}catch(e){toast(e.message,true)}};
function chooseEntityResult(index){let e=state.entityResults[index];if(e)chooseEntity(e.entity_id,e.name)}
function chooseEntity(id,name){for(let i=0;i<4;i++){let input=$('#entitySlots [name=id'+i+']');if(!input.value){input.value=id;$('#entitySlots [name=name'+i+']').value=name;return}}toast('All four entity slots are full',true)}
$('#haForm').onsubmit=async e=>{e.preventDefault();let p=new URLSearchParams(new FormData(e.currentTarget));try{await api('/save',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p.toString()});toast('Home Assistant configuration saved');loadDevices();loadHa()}catch(e){toast(e.message,true)}};
$('#exitPortal').onclick=async()=>{if(!confirm('Exit Portal and return Ble(e)p to normal control?'))return;try{await api('/api/exit',{method:'POST',body:{}});document.body.innerHTML='<main style="max-width:620px;margin:15vh auto;padding:24px"><div class="kicker">Portal closed</div><h1 style="font:800 54px var(--display)">BACK TO THE PANEL</h1><p>Wi-Fi and the administration server are shutting down.</p></main>'}catch(e){toast(e.message,true)}};
loadSummary();loadDevices();loadSequences();
</script></body></html>)HTML";

}  // namespace portal::assets
